# nixpacks.toml - Railway deployment configuration for Playwright support

[phases.install]
cmds = [
    # Install Python dependencies using python -m pip (more reliable)
    "python -m pip install -r requirements.txt",
    # Install Playwright browsers
    "python -m playwright install chromium",
    # Let Playwright install its own system dependencies  
    "python -m playwright install-deps chromium"
]

[start]
cmd = "uvicorn enhanced_server:app --host 0.0.0.0 --port $PORT"

[variables]
# Set environment variables for headless browser operation
DISPLAY = ":99"
PLAYWRIGHT_BROWSERS_PATH = "/opt/railway/app/.playwright"