# nixpacks.toml - Railway deployment configuration for Playwright support

[phases.setup]
aptPkgs = [
    # Core system dependencies
    "libglib2.0-0",
    "libnss3",
    "libnspr4", 
    "libdbus-1-3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libxcb1",
    "libxkbcommon0",
    "libatspi2.0-0",
    "libx11-6",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxrandr2",
    "libgbm1",
    "libpango-1.0-0",
    "libcairo2",
    "libasound2",
    # Additional dependencies for Chrome/Chromium
    "libgtk-3-0",
    "libxss1",
    "libgconf-2-4",
    "libxtst6",
    "fonts-liberation",
    "libappindicator3-1",
    "libasound2-dev",
    "xvfb"
]

[phases.install]
cmds = [
    # Install Python dependencies
    "pip install -r requirements.txt",
    # Install Playwright browsers
    "playwright install chromium",
    # Install Playwright system dependencies
    "playwright install-deps chromium"
]

[start]
cmd = "uvicorn enhanced_server:app --host 0.0.0.0 --port $PORT"

[variables]
# Set environment variables for headless browser operation
DISPLAY = ":99"
PLAYWRIGHT_BROWSERS_PATH = "/opt/railway/app/.playwright"